/* Весь текст сайта и метаданные игр — единственный источник правды.
   Отсюда генератор собирает страницы, sitemap, llms.txt и games.json. */

const SITE = {
  name: 'GamesIO',
  // Основной адрес. Меняется в одном месте — попадает в canonical, og:url и sitemap.
  url: 'https://aleksandr-litvinenko.github.io/GamesIO',
  repo: 'https://github.com/Aleksandr-Litvinenko/GamesIO',
  author: 'Aleksandr Litvinenko',
  // Локали: ключ → префикс пути. Пустой префикс = корень сайта.
  locales: { en: '', ru: 'ru' },
  defaultLocale: 'en',
};

const UI = {
  ru: {
    lang: 'ru',
    localeTag: 'ru_RU',
    langName: 'Русский',
    tagline: 'мини-игры в браузере',
    siteTitle: 'GamesIO — мини-игры в браузере: арканоид, змейка, мотоциклы',
    siteDescription:
      'Три классические мини-игры прямо в браузере: арканоид, змейка и световые мотоциклы. Без регистрации, без установки, бесплатно. Работают на телефоне и компьютере.',
    heroEyebrow: 'Вставьте монету',
    heroTitle: 'Мини-игры,<br>которые открываются<br><em>за одну секунду</em>',
    heroText:
      'Ни установки, ни регистрации, ни загрузок. Каждый экран ниже — живая игра на автопилоте: нажмите, чтобы сесть за руль. Рекорды сохраняются прямо в браузере.',
    catalogTitle: 'Каталог игр',
    searchLabel: 'Поиск по играм',
    searchPlaceholder: 'Найти игру…',
    filterAll: 'Все',
    nothingFound: 'Ничего не нашлось. Попробуйте другое слово.',
    playCta: 'Играть',
    record: 'Рекорд',
    noRecord: 'Ещё не играли',
    demoMode: 'Демо-режим',
    home: 'Главная',
    games: 'Игры',
    howToPlay: 'Как играть',
    controls: 'Управление',
    tips: 'Советы',
    about: 'Об игре',
    faq: 'Частые вопросы',
    otherGames: 'Другие игры',
    backToCatalog: '← Все игры',
    restart: 'Заново',
    pause: 'Пауза',
    sound: 'Звук',
    footerAbout:
      'GamesIO — небольшой набор классических аркад, переписанных на чистом JavaScript. Открытый код, никаких трекеров, всё работает офлайн после первой загрузки.',
    footerLinks: 'Разделы',
    footerSource: 'Исходный код на GitHub',
    footerRights: 'Код открыт под лицензией MIT.',
    langSwitch: 'In English',
    profile: 'Профиль',
    yourName: 'Ваше имя',
    color: 'Цвет',
    profilesOnDevice: 'Профили на этом устройстве',
    addProfile: 'Добавить игрока',
    newPlayer: 'Новый игрок',
    remove: 'Удалить',
    profileOf: 'Профиль: {n}',
    leaderboard: 'Таблица лидеров',
    yourBest: 'Ваш лучший результат',
    outsideTop: 'Вы на {n}-м месте — до первой десятки ещё далеко',
    boardOffline: 'Таблица недоступна офлайн. Появится, когда будет сеть.',
    noScoresYet: 'Пока пусто — сыграйте, и результат появится здесь.',
    globalEmpty: 'Общая таблица пока пуста. Опубликуйте свой результат первым.',
    publishScore: '🏆 Опубликовать результат',
    placeInTable: 'Место в таблице устройства: {n}',
    offlineTitle: 'Офлайн и установка',
    offlineReady: 'Игры скачаны — запускаются мгновенно и работают без сети',
    offlineCaching: 'Скачиваем игры в браузер, чтобы они запускались без сети…',
    offlineBadge: 'Офлайн',
    installApp: 'Установить как приложение',
    installedAlready: 'Приложение уже установлено',
    installHint: 'В меню браузера выберите «Установить приложение» или «На экран Домой».',
    adLabel: 'Реклама',
    playNow: 'Играть сейчас',
    freeOnline: 'Бесплатно, без регистрации',
    // Строки, которые движок и игры рисуют внутри канваса и оверлеев
    game: {
      score: 'Очки',
      best: 'Рекорд',
      lives: 'Жизни',
      level: 'Уровень',
      length: 'Длина',
      apples: 'Яблок',
      round: 'Раунд',
      play: 'Играть',
      resume: 'Продолжить',
      restart: 'Заново',
      again: 'Ещё раз',
      menu: 'В меню',
      paused: 'Пауза',
      gameOver: 'Игра окончена',
      victory: 'Победа!',
      newRecord: '🎉 Новый рекорд!',
      recordIs: 'Рекорд: {n}',
      launch: 'Пробел или тап — запуск',
      boost: 'БУСТ · SHIFT',
      roundClear: 'РАУНД ПРОЙДЕН',
      crashed: 'ТЫ РАЗБИЛСЯ',
      nextRoundFaster: 'Раунд {n} — быстрее',
      livesLeft: 'Осталось жизней: {n}',
      levelsCleared: 'Пройдено уровней: {n}',
      snakeLength: 'Длина змейки: {n}',
      roundsCleared: 'Пройдено раундов: {n}',
      perfectSnake: 'Поле заполнено — идеальная змейка!',
      time: 'Время',
      speed: 'Скорость',
      lap: 'Круг',
      overtakes: 'Обгоны',
      checkpoint: 'КОНТРОЛЬНАЯ ТОЧКА',
      distanceCovered: 'Пройдено {n} км',
      playerN: 'ИГРОК {n}',
      playerWins: 'ПОБЕДИЛ ИГРОК {n}',
      go: 'СТАРТ',
      p1: 'Игрок 1',
      p2: 'Игрок 2',
      wave: 'Волна',
      waveN: 'ВОЛНА {n}',
      bossIncoming: 'ВНИМАНИЕ: БОСС',
      wavesCleared: 'Пройдено волн: {n}',
      base: 'База',
      baseLost: 'База уничтожена',
      weapon: 'Оружие',
      bossDown: 'Босс повержен!',
      levelProgress: 'Пройдено {n}% уровня',
      rings: 'Кольца',
      rolling: 'В КЛУБКЕ',
      finishedIn: 'Финиш за {n} с',
      allZonesCleared: 'Все пять зон пройдены!',
      zoneN: 'ЗОНА {n}',
      zone: 'Зона',
      weaponUp: 'ОРУЖИЕ · УРОВЕНЬ {n}',
    },
  },
  en: {
    lang: 'en',
    localeTag: 'en_US',
    langName: 'English',
    tagline: 'mini-games in your browser',
    siteTitle: 'GamesIO — free browser mini-games: breakout, snake, light cycles',
    siteDescription:
      'Three classic mini-games right in your browser: breakout, snake and light cycles. No sign-up, no install, completely free. Works on phone and desktop.',
    heroEyebrow: 'Insert coin',
    heroTitle: 'Mini-games that open<br><em>in one second</em>',
    heroText:
      'No install, no sign-up, no downloads. Every screen below is a live game on autopilot — click one to take the wheel. High scores are saved right in your browser.',
    catalogTitle: 'Game catalogue',
    searchLabel: 'Search games',
    searchPlaceholder: 'Find a game…',
    filterAll: 'All',
    nothingFound: 'Nothing matched. Try another word.',
    playCta: 'Play',
    record: 'Best',
    noRecord: 'Not played yet',
    demoMode: 'Demo mode',
    home: 'Home',
    games: 'Games',
    howToPlay: 'How to play',
    controls: 'Controls',
    tips: 'Tips',
    about: 'About the game',
    faq: 'FAQ',
    otherGames: 'More games',
    backToCatalog: '← All games',
    restart: 'Restart',
    pause: 'Pause',
    sound: 'Sound',
    footerAbout:
      'GamesIO is a small set of classic arcade games rewritten in plain JavaScript. Open source, no trackers, and everything runs offline after the first load.',
    footerLinks: 'Sections',
    footerSource: 'Source code on GitHub',
    footerRights: 'Code released under the MIT licence.',
    langSwitch: 'По-русски',
    profile: 'Profile',
    yourName: 'Your name',
    color: 'Colour',
    profilesOnDevice: 'Profiles on this device',
    addProfile: 'Add player',
    newPlayer: 'New player',
    remove: 'Remove',
    profileOf: 'Profile: {n}',
    leaderboard: 'Leaderboard',
    yourBest: 'Your best score',
    outsideTop: 'You are #{n} — not in the top ten yet',
    boardOffline: 'The table is unavailable offline. It will appear once you are back online.',
    noScoresYet: 'Nothing here yet — play a round and your score appears.',
    globalEmpty: 'The global table is empty. Be the first to publish a score.',
    publishScore: '🏆 Publish score',
    placeInTable: 'Place on this device: {n}',
    offlineTitle: 'Offline and install',
    offlineReady: 'Games downloaded — they start instantly and work with no network',
    offlineCaching: 'Downloading the games into your browser so they run offline…',
    offlineBadge: 'Offline',
    installApp: 'Install as an app',
    installedAlready: 'Already installed',
    installHint: 'Use your browser menu: “Install app” or “Add to Home Screen”.',
    adLabel: 'Advertisement',
    playNow: 'Play now',
    freeOnline: 'Free, no sign-up',
    game: {
      score: 'Score',
      best: 'Best',
      lives: 'Lives',
      level: 'Level',
      length: 'Length',
      apples: 'Apples',
      round: 'Round',
      play: 'Play',
      resume: 'Resume',
      restart: 'Restart',
      again: 'Play again',
      menu: 'Back to games',
      paused: 'Paused',
      gameOver: 'Game over',
      victory: 'You win!',
      newRecord: '🎉 New best score!',
      recordIs: 'Best: {n}',
      launch: 'Space or tap to launch',
      boost: 'BOOST · SHIFT',
      roundClear: 'ROUND CLEARED',
      crashed: 'YOU CRASHED',
      nextRoundFaster: 'Round {n} — faster',
      livesLeft: 'Lives left: {n}',
      levelsCleared: 'Levels cleared: {n}',
      snakeLength: 'Snake length: {n}',
      roundsCleared: 'Rounds cleared: {n}',
      perfectSnake: 'Grid filled — a perfect snake!',
      time: 'Time',
      speed: 'Speed',
      lap: 'Lap',
      overtakes: 'Overtakes',
      checkpoint: 'CHECKPOINT',
      distanceCovered: '{n} km covered',
      playerN: 'PLAYER {n}',
      playerWins: 'PLAYER {n} WINS',
      go: 'GO',
      p1: 'Player 1',
      p2: 'Player 2',
      wave: 'Wave',
      waveN: 'WAVE {n}',
      bossIncoming: 'WARNING: BOSS',
      wavesCleared: 'Waves cleared: {n}',
      base: 'Base',
      baseLost: 'Base destroyed',
      weapon: 'Weapon',
      bossDown: 'Boss down!',
      levelProgress: '{n}% of the level cleared',
      rings: 'Rings',
      rolling: 'ROLLING',
      finishedIn: 'Finished in {n}s',
      allZonesCleared: 'All five zones cleared!',
      zoneN: 'ZONE {n}',
      zone: 'Zone',
      weaponUp: 'WEAPON · LEVEL {n}',
    },
  },
};

const CATEGORIES = {
  ru: {
    arcade: 'Аркада',
    classic: 'Классика',
    versus: 'Против ботов',
    retro: 'Ретро',
    racing: 'Гонки',
    shooter: 'Шутер',
    platformer: 'Платформер',
    strategy: 'Тактика',
    pseudo3d: '3D',
    twoPlayer: 'На двоих',
  },
  en: {
    arcade: 'Arcade',
    classic: 'Classic',
    versus: 'Versus bots',
    retro: 'Retro',
    racing: 'Racing',
    shooter: 'Shooter',
    platformer: 'Platformer',
    strategy: 'Tactics',
    pseudo3d: '3D',
    twoPlayer: 'Two players',
  },
};

const GAMES = [
  {
    id: 'arkanoid',
    emoji: '🧱',
    accent: '#22d3ee',
    categories: ['arcade', 'classic', 'retro'],
    released: '2026-08-04',
    ru: {
      title: 'Арканоид',
      slug: 'arkanoid',
      short: 'Разбей все кирпичи, лови бонусы и не теряй мяч.',
      metaTitle: 'Арканоид — играть онлайн бесплатно, без регистрации | GamesIO',
      metaDescription:
        'Классический арканоид в браузере: 5 уровней, пять видов бонусов, мультимяч и неразрушимые блоки. Управление мышью или стрелками, работает на телефоне. Играть бесплатно.',
      keywords: ['арканоид', 'арканоид играть', 'breakout онлайн', 'игра в кирпичики', 'арканоид бесплатно'],
      about: [
        'Арканоид родился в 1986 году как развитие Breakout: к простой связке «платформа и мяч» добавили бонусы, разные типы блоков и уровни со своим рисунком. Эта версия следует той же логике — вы отбиваете мяч платформой и выбиваете кирпичную стену, но каждый уровень требует своей траектории.',
        'Главный приём — угол отскока. Мяч уходит от платформы тем круче, чем дальше от центра вы его приняли: центр отправляет почти вертикально, край — почти горизонтально. Именно так пробивают проход к верхнему ряду и оставляют мяч работать под потолком, где он выбивает по несколько кирпичей за один заход.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>→</kbd> или мышь — двигать платформу',
        '<kbd>Пробел</kbd> или тап по экрану — запустить мяч',
        '<kbd>P</kbd> или <kbd>Esc</kbd> — пауза',
      ],
      tips: [
        'Принимайте мяч краем платформы, когда нужен резкий угол, и центром — когда хотите вернуть его строго вверх.',
        'Зелёный бонус <b>E</b> расширяет платформу, красный <b>S</b> сужает: под красный лучше не подставляться специально.',
        'Бонус <b>M</b> делит мяч на несколько — самый быстрый способ дочистить уровень, но следить придётся за всеми сразу.',
        'Серые блоки не разбиваются никогда. Считайте их частью стен и стройте траекторию вокруг.',
        'За каждый пройденный уровень дают 200 очков плюс 60 за каждую оставшуюся жизнь — рисковать ради бонуса не всегда выгодно.',
      ],
      faq: [
        {
          q: 'Сколько в игре уровней?',
          a: 'Пять разных раскладок, после чего они повторяются по кругу, но скорость мяча каждый раз растёт. Формально игра бесконечная — предел ставит только реакция.',
        },
        {
          q: 'Что делают падающие бонусы?',
          a: 'E расширяет платформу, S сужает, M делит мяч, L даёт дополнительную жизнь, W замедляет мяч на восемь секунд. Любой пойманный бонус приносит ещё 50 очков.',
        },
        {
          q: 'Можно ли играть с телефона?',
          a: 'Да. Платформа следует за пальцем, а тап по экрану запускает мяч. Отдельная раскладка кнопок не нужна.',
        },
        {
          q: 'Игра сохраняет прогресс?',
          a: 'Сохраняется рекорд — он лежит в localStorage вашего браузера и никуда не отправляется. Текущая партия при закрытии вкладки теряется.',
        },
      ],
    },
    en: {
      title: 'Breakout',
      slug: 'breakout',
      short: 'Clear every brick, catch power-ups and never drop the ball.',
      metaTitle: 'Breakout — play online free, no sign-up | GamesIO',
      metaDescription:
        'Classic breakout in your browser: 5 levels, five power-up types, multiball and indestructible blocks. Mouse or arrow keys, works on mobile. Play free.',
      keywords: ['breakout game', 'play breakout online', 'arkanoid online', 'brick breaker', 'free breakout'],
      about: [
        'Breakout arrived in 1976 and Arkanoid refined it a decade later by adding power-ups, block types and levels with their own shapes. This version follows the same idea: you bounce a ball off a paddle to demolish a brick wall, and each layout asks for a different angle of attack.',
        'The core skill is controlling the bounce. The ball leaves the paddle at a sharper angle the further from the centre you catch it — the middle sends it almost straight up, the edge sends it nearly sideways. That is how you carve a tunnel to the top row and leave the ball working under the ceiling, clearing several bricks per pass.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>→</kbd> or mouse — move the paddle',
        '<kbd>Space</kbd> or tap the screen — launch the ball',
        '<kbd>P</kbd> or <kbd>Esc</kbd> — pause',
      ],
      tips: [
        'Catch the ball on the edge of the paddle for a sharp angle, and in the centre when you want it straight back up.',
        'The green <b>E</b> power-up widens the paddle and the red <b>S</b> shrinks it — never chase the red one on purpose.',
        'The <b>M</b> power-up splits the ball into several. It is the fastest way to finish a level, but you have to track all of them.',
        'Grey blocks never break. Treat them as walls and plan your angles around them.',
        'Clearing a level pays 200 points plus 60 per remaining life, so a risky power-up grab is not always worth it.',
      ],
      faq: [
        {
          q: 'How many levels are there?',
          a: 'Five distinct layouts that then repeat, with the ball speeding up on every loop. In practice the game is endless — only your reflexes cap the score.',
        },
        {
          q: 'What do the falling power-ups do?',
          a: 'E widens the paddle, S shrinks it, M splits the ball, L grants an extra life, and W slows the ball for eight seconds. Any caught power-up is also worth 50 points.',
        },
        {
          q: 'Can I play on a phone?',
          a: 'Yes. The paddle follows your finger and a tap launches the ball, so no on-screen buttons are needed.',
        },
        {
          q: 'Does the game save progress?',
          a: 'Your best score is saved in your browser via localStorage and is never uploaded anywhere. The current run is lost when you close the tab.',
        },
      ],
    },
  },
  {
    id: 'snake',
    emoji: '🐍',
    accent: '#4ade80',
    categories: ['arcade', 'classic', 'retro'],
    released: '2026-08-04',
    ru: {
      title: 'Змейка',
      slug: 'zmeyka',
      short: 'Ешь яблоки, расти и не врезайся в себя. Золотое яблоко даёт +50.',
      metaTitle: 'Змейка — играть онлайн бесплатно, классическая игра | GamesIO',
      metaDescription:
        'Классическая змейка в браузере на поле 20×20: плавное движение, ускорение по мере роста и золотое яблоко на таймере. Стрелки, WASD или свайпы. Играть бесплатно.',
      keywords: ['змейка', 'змейка играть', 'игра змейка онлайн', 'snake игра', 'змейка бесплатно'],
      about: [
        'Змейка стала массовой в 1997 году вместе с Nokia 6110, хотя сама идея старше на два десятилетия. Правила не изменились: змея ползёт вперёд без остановки, каждое съеденное яблоко удлиняет её, а собственный хвост со временем превращается в главную опасность.',
        'Эта версия идёт на поле 20×20 со скоростью, которая растёт с каждым яблоком — от 0,145 секунды на клетку до 0,058. Раз в пять яблок появляется золотое: оно стоит 50 очков вместо 10 и живёт всего шесть с половиной секунд, так что за ним приходится идти на риск.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> или <kbd>WASD</kbd> — поворот',
        'Свайп в любую сторону — поворот на телефоне',
        '<kbd>P</kbd> или <kbd>Esc</kbd> — пауза',
      ],
      tips: [
        'Ходите вдоль стен и складывайте тело плотными рядами — так в центре остаётся место для манёвра.',
        'Повороты можно ставить в очередь: два быстрых нажатия подряд не потеряются, змейка выполнит оба.',
        'Золотое яблоко мигает за две секунды до исчезновения. Если к этому моменту вы не рядом — не идите за ним.',
        'Никогда не заходите в тупик, из которого нет выхода длиной больше вашего тела: развернуться на 180° нельзя.',
        'Чем длиннее змейка, тем быстрее она ползёт. Планируйте маршрут на пару ходов вперёд, а не по одному.',
      ],
      faq: [
        {
          q: 'Змейка проходит сквозь стены?',
          a: 'Нет, это классический вариант: удар о стену или о собственный хвост заканчивает партию.',
        },
        {
          q: 'Зачем нужно золотое яблоко?',
          a: 'Оно даёт 50 очков вместо обычных 10 и появляется после каждого пятого съеденного яблока. Но живёт всего 6,5 секунды и исчезает.',
        },
        {
          q: 'Игра ускоряется?',
          a: 'Да, каждое яблоко немного сокращает время хода — от 0,145 до 0,058 секунды на клетку. К пятидесятому яблоку темп становится заметно жёстче.',
        },
        {
          q: 'Какой максимальный счёт?',
          a: 'Поле 20×20, то есть 400 клеток. Если заполнить его целиком, игра засчитывает победу — но на практике это почти недостижимо.',
        },
      ],
    },
    en: {
      title: 'Snake',
      slug: 'snake',
      short: 'Eat apples, grow longer and never bite yourself. Golden apples pay +50.',
      metaTitle: 'Snake — play the classic game online free | GamesIO',
      metaDescription:
        'Classic snake in your browser on a 20×20 grid: smooth movement, speed that ramps as you grow, and a timed golden apple. Arrows, WASD or swipes. Play free.',
      keywords: ['snake game', 'play snake online', 'classic snake', 'snake game free', 'nokia snake'],
      about: [
        'Snake went mainstream in 1997 on the Nokia 6110, though the idea is two decades older. The rules never changed: the snake moves forward without stopping, every apple makes it longer, and your own tail eventually becomes the real hazard.',
        'This version runs on a 20×20 grid at a pace that tightens with every apple — from 0.145 seconds per cell down to 0.058. Every fifth apple spawns a golden one worth 50 points instead of 10, but it only lives six and a half seconds, so collecting it always costs you some risk.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> or <kbd>WASD</kbd> — turn',
        'Swipe in any direction — turn on mobile',
        '<kbd>P</kbd> or <kbd>Esc</kbd> — pause',
      ],
      tips: [
        'Hug the walls and stack your body in tight rows so the centre stays open for manoeuvring.',
        'Turns are queued: two quick presses in a row are both remembered, so fast double turns work.',
        'The golden apple blinks two seconds before it vanishes. If you are not close by then, let it go.',
        'Never enter a dead end shorter than your own body — you cannot turn 180 degrees to escape.',
        'The longer the snake, the faster it moves. Plan two moves ahead rather than one.',
      ],
      faq: [
        {
          q: 'Does the snake wrap around the walls?',
          a: 'No — this is the classic ruleset. Hitting a wall or your own tail ends the run.',
        },
        {
          q: 'What is the golden apple for?',
          a: 'It pays 50 points instead of the usual 10 and appears after every fifth apple eaten. It only lasts 6.5 seconds before disappearing.',
        },
        {
          q: 'Does the game get faster?',
          a: 'Yes. Each apple shortens the step time from 0.145 down to 0.058 seconds per cell, so by the fiftieth apple the pace is genuinely demanding.',
        },
        {
          q: 'What is the maximum score?',
          a: 'The grid is 20×20, so 400 cells. Filling it completely counts as a win, though in practice that is nearly unreachable.',
        },
      ],
    },
  },
  {
    id: 'moto',
    emoji: '🏍️',
    accent: '#a78bfa',
    categories: ['arcade', 'versus', 'retro'],
    released: '2026-08-04',
    ru: {
      title: 'Змеиные войны',
      slug: 'snake-wars',
      short: 'Световые мотоциклы: оставляй стену за собой и переживи трёх ботов.',
      metaTitle: 'Змеиные войны — световые мотоциклы против ботов, играть бесплатно | GamesIO',
      metaDescription:
        'Световые мотоциклы в стиле Tron: вы против трёх ботов на арене 40×40. Стена за спиной, буст на Shift, раунды с ростом скорости. Играть в браузере бесплатно.',
      keywords: ['змеиные войны', 'световые мотоциклы', 'трон игра', 'snake wars', 'змейка против ботов'],
      about: [
        'Жанр вырос из фильма «Трон» 1982 года: мотоцикл едет без остановки и оставляет за собой сплошную световую стену. Проигрывает тот, кто первым в такую стену врежется — свою, чужую или границу арены. Здесь вы выходите на поле 40×40 против трёх ботов сразу.',
        'Боты не ездят по скрипту: перед каждым ходом каждый из них считает длину свободного коридора впереди и объём доступной области с трёх сторон, а если вы оказались рядом — сознательно подрезает. Поэтому одна и та же тактика дважды не сработает, а раунд обычно решается за 20–25 секунд.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> или <kbd>WASD</kbd> — поворот',
        '<kbd>Shift</kbd> — буст, тратит энергию из шкалы внизу',
        'Тап по левой или правой половине экрана — поворот на телефоне',
        '<kbd>P</kbd> или <kbd>Esc</kbd> — пауза',
      ],
      tips: [
        'Не рвитесь в центр на старте. Тесная спираль вдоль своей половины арены экономит место, которое понадобится в конце раунда.',
        'Буст — не для скорости, а для отрезания. Им удобно захлопнуть петлю раньше, чем бот успеет из неё выйти.',
        'Боты жадные до свободного места: если оставить им узкий коридор и широкий соблазн рядом, они сами загонят себя в тупик.',
        'Энергия буста восстанавливается примерно втрое медленнее, чем тратится. Держите запас на последние секунды раунда.',
        'За каждого разбившегося бота дают 150 очков, а за выигранный раунд — 500, умноженные на номер раунда. Дожить до пятого выгоднее, чем собрать все убийства в первом.',
      ],
      faq: [
        {
          q: 'Сколько ботов на арене?',
          a: 'Трое. Раунд считается выигранным, когда все три разбились, а вы остались живы.',
        },
        {
          q: 'Как работает буст?',
          a: 'Пока держите Shift, мотоцикл едет почти вдвое быстрее и тратит энергию из шкалы внизу экрана. Она восстанавливается сама, но медленно.',
        },
        {
          q: 'Игра становится сложнее?',
          a: 'Да, с каждым раундом шаг сокращается — от 0,075 до 0,04 секунды на клетку. У вас три жизни на всю партию.',
        },
        {
          q: 'Можно ли развернуться назад?',
          a: 'Нет. Поворот на 180 градусов заблокирован — это привело бы к мгновенному столкновению с собственной стеной.',
        },
      ],
    },
    en: {
      title: 'Snake Wars',
      slug: 'snake-wars',
      short: 'Tron-style light cycles: leave a wall behind you and outlast three bots.',
      metaTitle: 'Snake Wars — light cycles against bots, play online free | GamesIO',
      metaDescription:
        'Tron-style light cycles: you against three bots on a 40×40 arena. Solid light wall behind you, Shift to boost, rounds that keep getting faster. Play free in your browser.',
      keywords: ['snake wars game', 'light cycles game', 'tron game online', 'snake vs bots', 'light bike game'],
      about: [
        'The genre comes straight out of Tron (1982): the cycle never stops and leaves a solid wall of light behind it. Whoever hits a wall first — their own, someone else’s, or the arena edge — is out. Here you take a 40×40 arena against three bots at once.',
        'The bots do not follow a script. Before every move each one measures the length of the open corridor ahead and the amount of reachable space in three directions, and if you are close it will deliberately cut you off. The same trick rarely works twice, and a round usually resolves in 20–25 seconds.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> or <kbd>WASD</kbd> — turn',
        '<kbd>Shift</kbd> — boost, drains the energy bar at the bottom',
        'Tap the left or right half of the screen — turn on mobile',
        '<kbd>P</kbd> or <kbd>Esc</kbd> — pause',
      ],
      tips: [
        'Do not rush the centre at the start. A tight spiral in your own half banks the space you will need at the end of the round.',
        'Boost is for cutting off, not for speed. Use it to close a loop before a bot can escape it.',
        'Bots are greedy for open space: leave them a narrow corridor next to a tempting opening and they will trap themselves.',
        'Boost energy regenerates about three times slower than it drains, so keep a reserve for the final seconds.',
        'Each crashed bot pays 150 points and a won round pays 500 × the round number, so surviving to round five beats farming kills in round one.',
      ],
      faq: [
        {
          q: 'How many bots are on the arena?',
          a: 'Three. A round is won when all three have crashed and you are still riding.',
        },
        {
          q: 'How does the boost work?',
          a: 'Holding Shift moves your cycle almost twice as fast while draining the energy bar at the bottom. It refills on its own, but slowly.',
        },
        {
          q: 'Does the game get harder?',
          a: 'Yes — each round shortens the step from 0.075 down to 0.04 seconds per cell. You get three lives for the whole session.',
        },
        {
          q: 'Can I turn back on myself?',
          a: 'No. A 180-degree turn is blocked, since it would mean instantly crashing into your own wall.',
        },
      ],
    },
  },
  {
    id: 'planes',
    emoji: '✈️',
    accent: '#38bdf8',
    categories: ['arcade', 'shooter', 'retro'],
    released: '2026-08-04',
    ru: {
      title: 'Самолётики',
      slug: 'samolyotiki',
      short: 'Вертикальный скролл-шутер: волны, бонусы и босс каждую пятую волну.',
      metaTitle: 'Самолётики — играть онлайн бесплатно, аркадный шутер | GamesIO',
      metaDescription:
        'Классические самолётики в браузере: волны противников, три типа поведения, бонусы на разброс и щит, босс каждую пятую волну. Управление пальцем или стрелками. Играть бесплатно.',
      keywords: ['самолётики', 'игра самолётики', 'аркадный шутер онлайн', '1942 игра', 'самолеты стрелялка браузер'],
      about: [
        'Жанр задал автомат 1942 года выпуска 1984 года: экран прокручивается сам, самолёт держится внизу, а сверху накатывают волны противников. Формула оказалась настолько устойчивой, что дожила без изменений до мобильных игр — меняются только количество пуль на экране и разрешение.',
        'Здесь три типа противников. Прямые идут вниз по своей полосе, зигзаги виляют и стреляют по вам с упреждением, пикировщики разгоняются и доворачивают в вашу сторону. Каждая пятая волна — босс с полосой здоровья, который бьёт веером из трёх пуль. Стрельба идёт сама: держать ещё и кнопку огня на телефоне невозможно.',
      ],
      controls: [
        'Палец или мышь — самолёт летит за курсором',
        '<kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> или <kbd>WASD</kbd> — движение',
        'Стрельба автоматическая',
        '<kbd>P</kbd> или <kbd>Esc</kbd> — пауза',
      ],
      tips: [
        'Не стойте по центру: пикировщики целятся туда, где вы были секунду назад, и уход вбок почти всегда спасает.',
        'Бонус <b>W</b> даёт разброс на 12 секунд — под него выгодно вытягивать волну, а не добивать одиночек.',
        'Щит <b>S</b> держит ровно одно попадание. Перед боссом его лучше приберечь.',
        'Босс ходит по горизонтали: держитесь под ним по диагонали, тогда веер из трёх пуль пройдёт мимо.',
        'За зачистку волны дают 100 очков на её номер, поэтому дожить до десятой волны выгоднее, чем настрелять мелочи в первых трёх.',
      ],
      faq: [
        {
          q: 'Нужно ли нажимать на огонь?',
          a: 'Нет, стрельба автоматическая. Так игра одинаково удобна и с клавиатуры, и с телефона, где второй палец занят.',
        },
        {
          q: 'Как часто появляется босс?',
          a: 'Каждая пятая волна. Его здоровье и темп стрельбы растут с номером волны, а после смерти он всегда роняет бонус.',
        },
        {
          q: 'Что делают бонусы?',
          a: 'W — тройной разброс на 12 секунд, S — щит на одно попадание, ♥ — дополнительная жизнь. Любой подобранный бонус даёт ещё 50 очков.',
        },
        {
          q: 'Игра когда-нибудь заканчивается?',
          a: 'Только когда закончатся жизни. Волны идут бесконечно, становясь плотнее и быстрее.',
        },
      ],
    },
    en: {
      title: 'Sky Squadron',
      slug: 'sky-squadron',
      short: 'Vertical scrolling shooter: waves, power-ups and a boss every fifth wave.',
      metaTitle: 'Sky Squadron — play the arcade plane shooter online free | GamesIO',
      metaDescription:
        'Classic plane shooter in your browser: enemy waves, three behaviours, spread and shield power-ups, a boss every fifth wave. Play with finger or arrow keys, free.',
      keywords: ['plane shooter game', 'arcade shmup online', '1942 game', 'airplane game free', 'vertical shooter browser'],
      about: [
        'The genre was defined by 1942, the 1984 arcade cabinet: the screen scrolls by itself, your plane sits near the bottom, and waves roll in from the top. The formula proved so durable that it reached mobile unchanged — only the bullet count and the resolution moved on.',
        'There are three enemy behaviours here. Straight flyers ride their lane down, zigzags weave and lead their shots, and divers accelerate and turn toward you. Every fifth wave brings a boss with a health bar that fires a three-shot fan. Your own gun is automatic: holding a fire button as well is impossible on a phone.',
      ],
      controls: [
        'Finger or mouse — the plane follows your pointer',
        '<kbd>←</kbd> <kbd>→</kbd> <kbd>↑</kbd> <kbd>↓</kbd> or <kbd>WASD</kbd> — move',
        'Firing is automatic',
        '<kbd>P</kbd> or <kbd>Esc</kbd> — pause',
      ],
      tips: [
        'Do not sit in the centre: divers aim where you were a second ago, so a sideways move almost always saves you.',
        'The <b>W</b> power-up gives spread fire for 12 seconds — use it to clear a whole wave rather than mopping up stragglers.',
        'The <b>S</b> shield absorbs exactly one hit. Save it for the boss.',
        'The boss tracks sideways: stay diagonally below it so the three-shot fan passes either side of you.',
        'Clearing a wave pays 100 points times its number, so surviving to wave ten beats farming the first three.',
      ],
      faq: [
        {
          q: 'Do I need to press a fire button?',
          a: 'No, firing is automatic. That keeps the game equally playable on a keyboard and on a phone where your second thumb is busy.',
        },
        {
          q: 'How often does a boss appear?',
          a: 'Every fifth wave. Its health and rate of fire scale with the wave number, and it always drops a power-up when destroyed.',
        },
        {
          q: 'What do the power-ups do?',
          a: 'W is 12 seconds of triple spread fire, S is a shield that absorbs one hit, ♥ is an extra life. Any pickup is also worth 50 points.',
        },
        {
          q: 'Does the game ever end?',
          a: 'Only when you run out of lives. The waves keep coming, getting denser and faster.',
        },
      ],
    },
  },
  {
    id: 'tanks',
    emoji: '🚜',
    accent: '#fbbf24',
    categories: ['arcade', 'strategy', 'retro', 'classic'],
    released: '2026-08-04',
    ru: {
      title: 'Танчики',
      slug: 'tanchiki',
      short: 'Держи базу, круши кирпич и не пропусти танки с верхнего края.',
      metaTitle: 'Танчики — играть онлайн бесплатно, как на Денди | GamesIO',
      metaDescription:
        'Классические танчики с Денди в браузере: поле из кирпича и брони, база под защитой, волны вражеских танков. Стрелки и пробел или палец. Играть бесплатно.',
      keywords: ['танчики', 'танчики играть', 'battle city онлайн', 'танки денди', 'танчики бесплатно'],
      about: [
        'Battle City вышла в 1985 году и в России стала просто «танчиками» — игрой, в которую играли вдвоём на одном картридже. Правила держатся на одной идее: у вас есть база, и потерять её обиднее, чем потерять жизнь. Кирпичные стены вокруг неё разрушаются с обеих сторон, поэтому оборона всё время осыпается.',
        'Поле собрано из четвертинок кирпича, как в оригинале: одна пуля выбивает не всю стену, а только кусок, и через пару выстрелов появляется проход. Броня не пробивается вообще, вода не пропускает танк, но пропускает пулю, а в кустах танк не видно. Танки идут сверху и целятся в базу, но иногда сворачивают за вами.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> или <kbd>WASD</kbd> — движение',
        '<kbd>Пробел</kbd> — выстрел',
        'Касание экрана — танк едет к пальцу',
        '<kbd>P</kbd> или <kbd>Esc</kbd> — пауза',
      ],
      tips: [
        'Не разрушайте кирпич вокруг базы сами: каждая выбитая четвертинка — это дыра, через которую пройдёт чужая пуля.',
        'Броня не пробивается ничем, поэтому за ней можно пересидеть, пока перезаряжаетесь.',
        'Вода останавливает танк, но не пулю. Через неё удобно расстреливать тех, кто не может подойти.',
        'В кустах вас не видно, но и вы стреляете вслепую — засада работает только если помнить, где противник.',
        'Розовые танки держат два попадания. Первым выстрелом они сбрасываются в обычные, добивать нужно сразу.',
      ],
      faq: [
        {
          q: 'Что происходит, если базу уничтожат?',
          a: 'Партия заканчивается сразу, сколько бы жизней ни оставалось. Это главное отличие жанра от обычной стрелялки.',
        },
        {
          q: 'Почему стена разрушается не целиком?',
          a: 'Каждый кирпичный блок состоит из четырёх четвертинок, и пуля выбивает только ту, в которую попала. Так было в оригинале — это позволяет прострелить узкую щель.',
        },
        {
          q: 'Сколько танков в волне?',
          a: 'Шесть плюс по одному за каждые две волны. Одновременно на поле не больше четырёх, остальные ждут очереди на респавн.',
        },
        {
          q: 'Можно играть вдвоём?',
          a: 'Пока нет, здесь один игрок против волн. Игра на двоих за одной клавиатурой есть в «Дуэли на двоих».',
        },
      ],
    },
    en: {
      title: 'Battle Tanks',
      slug: 'battle-tanks',
      short: 'Defend the base, blast through brick and stop the tanks rolling in from the top.',
      metaTitle: 'Battle Tanks — play the NES classic online free | GamesIO',
      metaDescription:
        'Classic NES tank battle in your browser: brick and steel maze, a base to defend, waves of enemy tanks. Arrow keys and space, or touch. Play free.',
      keywords: ['battle city game', 'tank game online', 'nes tanks', 'battle tanks free', 'retro tank game'],
      about: [
        'Battle City arrived in 1985 and became the game a generation played two-up on a single cartridge. It rests on one idea: you have a base, and losing it hurts more than losing a life. The brick around it can be shot from either side, so your defences crumble all game long.',
        'The field is made of brick quarters, exactly as in the original: one bullet knocks out a piece rather than a whole wall, and a couple of shots opens a gap. Steel cannot be destroyed at all, water stops tanks but not bullets, and bushes hide whoever is inside them. Enemy tanks head for your base but will sometimes turn to chase you.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>↑</kbd> <kbd>→</kbd> <kbd>↓</kbd> or <kbd>WASD</kbd> — move',
        '<kbd>Space</kbd> — fire',
        'Touch the screen — the tank drives toward your finger',
        '<kbd>P</kbd> or <kbd>Esc</kbd> — pause',
      ],
      tips: [
        'Do not shoot the brick around your own base: every quarter you remove is a hole an enemy bullet will use.',
        'Steel is indestructible, so you can sit behind it while your gun reloads.',
        'Water blocks tanks but not bullets, which makes it a safe firing line against anything that cannot reach you.',
        'Bushes hide you, but you shoot blind from inside them — an ambush only works if you remember where the enemy was.',
        'Pink tanks take two hits. The first shot downgrades them, so finish the job immediately.',
      ],
      faq: [
        {
          q: 'What happens if the base is destroyed?',
          a: 'The run ends immediately, no matter how many lives you have left. That is what separates this genre from a plain shooter.',
        },
        {
          q: 'Why does a wall not break all at once?',
          a: 'Each brick block is four quarters and a bullet only removes the one it hits. That is how the original worked, and it lets you shoot a narrow slit.',
        },
        {
          q: 'How many tanks are in a wave?',
          a: 'Six, plus one more for every two waves. No more than four are on the field at once; the rest queue for a spawn point.',
        },
        {
          q: 'Is there two-player mode?',
          a: 'Not here — this is one player against the waves. For local two-player, try Split Duel.',
        },
      ],
    },
  },
  {
    id: 'contra',
    emoji: '🔫',
    accent: '#22d3ee',
    categories: ['arcade', 'shooter', 'platformer', 'retro'],
    released: '2026-08-04',
    ru: {
      title: 'Десант',
      slug: 'desant',
      short: 'Беги вправо, стреляй в восьми направлениях и дойди до босса с одной жизнью за раз.',
      metaTitle: 'Десант — игра как Контра на Денди, играть онлайн бесплатно | GamesIO',
      metaDescription:
        'Беги-и-стреляй в духе Contra: восемь направлений огня, смерть от одного попадания, сквозные платформы, бонус на разброс и босс в конце уровня. Играть бесплатно.',
      keywords: ['контра игра', 'contra денди', 'беги и стреляй', 'платформер стрелялка онлайн', 'контра играть бесплатно'],
      about: [
        'Contra 1987 года собрала жанр из трёх решений: стрельба в восьми направлениях, смерть от одного попадания и уровень, который тянется вправо и заканчивается боссом. Комбинация оказалась настолько жёсткой и честной, что игру помнят до сих пор — в том числе за код на тридцать жизней.',
        'Здесь всё три на месте. Прицел встаёт по крестовине: вверх, вниз в прыжке и четыре диагонали. Сквозные платформы проходятся снизу, а «вниз плюс прыжок» роняет вас на ярус ниже — без этого на многоярусной карте не развернуться. Одно попадание — минус жизнь, поэтому бонус на разброс важнее любой тактики.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>→</kbd> — бег, <kbd>↑</kbd> <kbd>↓</kbd> — прицел',
        '<kbd>Пробел</kbd> — прыжок, <kbd>↓</kbd> + прыжок — вниз сквозь платформу',
        '<kbd>Shift</kbd> или касание — огонь',
        '<kbd>P</kbd> или <kbd>Esc</kbd> — пауза',
      ],
      tips: [
        'Стреляйте не переставая: патроны бесконечны, а лишняя пуля в воздухе часто снимает того, кого вы ещё не увидели.',
        'Диагональ вниз работает только в прыжке — это единственный способ достать пехоту с верхнего яруса.',
        'Бонус <b>S</b> даёт разброс на 14 секунд. С ним босса разбирают вдвое быстрее, поэтому к нему стоит подойти с бонусом.',
        'Турели не двигаются, но бьют с упреждением. Их проще проскочить в прыжке, чем расстреливать в лоб.',
        'После смерти вы возрождаетесь чуть позади, а не в начале уровня — потерянные метры отыгрываются за секунды.',
      ],
      faq: [
        {
          q: 'Правда одно попадание — и смерть?',
          a: 'Да, как в оригинале. Жизней три, и каждая заканчивается от любой пули или касания врага.',
        },
        {
          q: 'Как стрелять по диагонали вниз?',
          a: 'Только в прыжке: удерживайте «вниз» и сторону движения. На земле «вниз» уходит в приседание.',
        },
        {
          q: 'Что в конце уровня?',
          a: 'Босс с полосой здоровья, который бьёт веером из трёх пуль. За него дают три тысячи очков плюс премию за оставшиеся жизни.',
        },
        {
          q: 'Сколько идёт уровень?',
          a: 'Около минуты на пробежку, если не задерживаться. Полоса внизу экрана показывает, сколько осталось.',
        },
      ],
    },
    en: {
      title: 'Jungle Strike',
      slug: 'jungle-strike',
      short: 'Run right, shoot in eight directions and reach the boss on a one-hit life.',
      metaTitle: 'Jungle Strike — Contra-style run and gun online free | GamesIO',
      metaDescription:
        'Run-and-gun in the spirit of Contra: eight-way fire, one-hit deaths, drop-through platforms, a spread-gun pickup and a boss at the end. Play free in your browser.',
      keywords: ['contra game online', 'run and gun game', 'nes shooter browser', 'platform shooter free', 'retro run and gun'],
      about: [
        'Contra in 1987 built the genre out of three decisions: eight-way fire, death in one hit, and a level that runs right and ends with a boss. The combination was harsh and fair enough that people still remember it — including the thirty-lives code.',
        'All three are here. The aim snaps to the d-pad: up, down while airborne, and four diagonals. Platforms are passed from below, and “down plus jump” drops you a tier — without it a multi-level map is unplayable. One hit costs a life, which makes the spread pickup worth more than any tactic.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>→</kbd> — run, <kbd>↑</kbd> <kbd>↓</kbd> — aim',
        '<kbd>Space</kbd> — jump, <kbd>↓</kbd> + jump — drop through a platform',
        '<kbd>Shift</kbd> or touch — fire',
        '<kbd>P</kbd> or <kbd>Esc</kbd> — pause',
      ],
      tips: [
        'Never stop firing: ammo is infinite, and a stray bullet often kills something you have not spotted yet.',
        'Down-diagonal only works in the air — it is the only way to hit infantry from the tier above.',
        'The <b>S</b> pickup gives spread fire for 14 seconds. It halves the boss fight, so try to arrive still holding it.',
        'Turrets do not move but they lead their shots. Jumping past them is easier than trading fire head-on.',
        'After a death you respawn slightly behind, not at the start — the lost ground takes seconds to recover.',
      ],
      faq: [
        {
          q: 'Is it really one hit and you die?',
          a: 'Yes, as in the original. You get three lives and each ends to any bullet or enemy contact.',
        },
        {
          q: 'How do I shoot down-diagonally?',
          a: 'Only while airborne: hold down plus your direction of travel. On the ground, down means crouch.',
        },
        {
          q: 'What is at the end of the level?',
          a: 'A boss with a health bar that fires a three-shot fan. It pays three thousand points plus a bonus for lives in hand.',
        },
        {
          q: 'How long is the level?',
          a: 'About a minute if you keep moving. The bar at the bottom of the screen shows how much is left.',
        },
      ],
    },
  },
  {
    id: 'sonic',
    emoji: '💙',
    accent: '#2563eb',
    categories: ['arcade', 'platformer', 'retro'],
    released: '2026-08-04',
    ru: {
      title: 'Ёжик',
      slug: 'yozhik',
      short: 'Скоростной платформер: разгон под горку, клубок, кольца вместо здоровья.',
      metaTitle: 'Ёжик — игра как Соник, играть онлайн бесплатно | GamesIO',
      metaDescription:
        'Скоростной платформер в духе Sonic: инерция и уклоны, разгон в клубке, кольца вместо полоски здоровья, пружины и трамплины. Играть в браузере бесплатно.',
      keywords: ['соник игра', 'sonic играть онлайн', 'ёжик игра', 'скоростной платформер', 'соник бесплатно браузер'],
      about: [
        'Sonic 1991 года отличался от других платформеров одной вещью — уклоном. Земля здесь не набор ступенек, а кривая, и скорость зависит от того, куда эта кривая наклонена. Вниз ёж разгоняется сам, вверх теряет ход, и вся игра превращается в поиск траектории, на которой скорость не теряется.',
        'Поэтому уровень тут сделан не из тайлов, а из рельефа: для каждой колонки задана высота земли. В клубке трение почти исчезает, и накопленная на спуске скорость несёт через следующую горку — это главный приём. Кольца работают как броня: пока есть хоть одно, попадание не убивает, а рассыпает их по земле.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>→</kbd> — бег',
        '<kbd>Пробел</kbd> или <kbd>↑</kbd> — прыжок',
        '<kbd>↓</kbd> на скорости — свернуться в клубок',
        '<kbd>P</kbd> или <kbd>Esc</kbd> — пауза',
      ],
      tips: [
        'Не тормозите перед горкой — наоборот, разгонитесь на спуске перед ней: инерция вынесет наверх сама.',
        'Клубок почти не тормозит, но им нельзя рулить. Сворачивайтесь на спуске и разворачивайтесь только на ровном.',
        'Одно кольцо спасает от смерти так же, как двадцать. Но собранные кольца дают очки, а рассыпанные — нет.',
        'Врага можно снять сверху в прыжке или протаранить в клубке. В обычном беге касание отнимает кольца.',
        'За финиш дают премию за время: пробежать уровень за минуту выгоднее, чем собрать все кольца за три.',
      ],
      faq: [
        {
          q: 'Почему ёж разгоняется сам под горку?',
          a: 'Уклон добавляется к скорости каждый кадр — так же, как в оригинале. На спуске он прибавляет, на подъёме отнимает, поэтому траектория важнее кнопок.',
        },
        {
          q: 'Зачем нужны кольца?',
          a: 'Это здоровье. Пока есть хоть одно, попадание только рассыпает кольца. Без колец следующее попадание отнимает жизнь.',
        },
        {
          q: 'Как свернуться в клубок?',
          a: 'Нажмите «вниз» на скорости выше пешей. В клубке трение почти исчезает, но управление пропадает до остановки.',
        },
        {
          q: 'Уровень один?',
          a: 'Да, но он длинный и заканчивается финишным столбом. Очки складываются из колец, врагов и премии за время.',
        },
      ],
    },
    en: {
      title: 'Blue Dash',
      slug: 'blue-dash',
      short: 'Speed platformer: momentum on slopes, spin roll and rings instead of health.',
      metaTitle: 'Blue Dash — Sonic-style speed platformer online free | GamesIO',
      metaDescription:
        'Speed platformer in the spirit of Sonic: slope momentum, a spin roll that keeps your speed, rings instead of a health bar, springs and ramps. Play free in your browser.',
      keywords: ['sonic game online', 'speed platformer', 'hedgehog game free', 'retro platformer browser', 'sonic style game'],
      about: [
        'Sonic in 1991 differed from every other platformer in one way: slope. The ground is a curve rather than a staircase, and your speed depends on which way that curve tilts. Downhill you accelerate on your own, uphill you bleed speed, and the whole game becomes a hunt for the line that keeps momentum.',
        'That is why this level is built from terrain rather than tiles: every column has a ground height. Rolling nearly removes friction, so the speed you banked on a descent carries you over the next hill — that is the core trick. Rings act as armour: while you hold even one, a hit scatters them instead of killing you.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>→</kbd> — run',
        '<kbd>Space</kbd> or <kbd>↑</kbd> — jump',
        '<kbd>↓</kbd> at speed — curl into a roll',
        '<kbd>P</kbd> or <kbd>Esc</kbd> — pause',
      ],
      tips: [
        'Do not brake before a hill — build speed on the descent in front of it and momentum will carry you over.',
        'Rolling barely slows you but you cannot steer. Curl on descents and uncurl only on the flat.',
        'One ring saves you exactly as well as twenty. But collected rings score points and scattered ones do not.',
        'Enemies die to a jump from above or to a roll. Touching one while simply running costs you your rings.',
        'The finish pays a time bonus, so a one-minute run beats collecting every ring in three.',
      ],
      faq: [
        {
          q: 'Why does the hedgehog speed up downhill on its own?',
          a: 'The slope is added to your speed every frame, exactly as in the original. It gives on descents and takes on climbs, which makes your line matter more than your buttons.',
        },
        {
          q: 'What are the rings for?',
          a: 'They are your health. While you hold at least one, a hit only scatters them. With no rings, the next hit costs a life.',
        },
        {
          q: 'How do I roll?',
          a: 'Press down while moving faster than a walk. Rolling nearly removes friction but you lose steering until you stop.',
        },
        {
          q: 'Is there only one level?',
          a: 'Yes, but it is long and ends at a goal post. Your score combines rings, enemies and a time bonus.',
        },
      ],
    },
  },
  {
    id: 'moto3d',
    emoji: '🏁',
    accent: '#22d3ee',
    categories: ['racing', 'pseudo3d', 'arcade', 'retro'],
    released: '2026-08-04',
    ru: {
      title: 'Реальные мотоциклы',
      slug: 'moto-3d',
      short: 'Псевдо-3D гонка на байке: закат, трафик и таймер, который вечно кончается.',
      metaTitle: 'Гонки на мотоцикле 3D — играть онлайн бесплатно | GamesIO',
      metaDescription:
        'Аркадная гонка на мотоцикле от третьего лица, как на автоматах Sega: закат, повороты, встречный трафик и контрольные точки, продлевающие время. Играть в браузере бесплатно.',
      keywords: ['гонки на мотоцикле', 'мотогонки 3д', 'hang on игра', 'аркадные гонки онлайн', 'мотоцикл игра браузер'],
      about: [
        'В 1985 году Sega выпустила Hang-On — первую гонку, где мотоцикл нёсся навстречу горизонту, а игрок наклонялся вместе с корпусом автомата. Настоящей трёхмерной графики тогда не существовало: дорога собиралась из полос, которые быстро сменяли друг друга и создавали иллюзию скорости. Эта игра сделана тем же способом.',
        'Трасса нарезана на сегменты, каждый рисуется как трапеция, и поворот — это не геометрия, а сдвиг каждого следующего сегмента вбок. Отсюда и характерная физика: на скорости в повороте вас выносит наружу, и удержать байк можно только заранее прижавшись к внутренней стороне. Съезд на обочину мгновенно съедает скорость, а таймер продлевается только на контрольных точках.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>→</kbd> — наклон и руль',
        '<kbd>↑</kbd> или <kbd>Пробел</kbd> — газ, <kbd>↓</kbd> — тормоз',
        'Касание экрана — газ, движение пальцем влево-вправо — руль',
        '<kbd>P</kbd> или <kbd>Esc</kbd> — пауза',
      ],
      tips: [
        'В повороте прижимайтесь к внутренней стороне заранее: центробежная сила растёт вместе со скоростью, и на максимуме вас вынесет с полотна.',
        'Тормоз почти не нужен. Быстрее объехать машину, чем оттормаживаться — потерянную скорость набирать долго.',
        'Обочина отнимает скорость только выше трети от максимума. На медленном ходу по ней можно спрямить поворот.',
        'Контрольная точка даёт +22 секунды. Их четыре на круг, так что цель — не проехать красиво, а успеть до следующей.',
        'Грузовики шире легковушек и едут медленнее — самый опасный тип трафика в слепом повороте.',
      ],
      faq: [
        {
          q: 'Это настоящая 3D-графика?',
          a: 'Нет, и в оригинальных автоматах Sega её тоже не было. Дорога собирается из плоских сегментов, которые проецируются на экран — приём называется псевдо-3D. Поэтому игра работает без WebGL и грузится мгновенно.',
        },
        {
          q: 'Что даёт контрольная точка?',
          a: 'Плюс 22 секунды к таймеру и 200 очков. Отметки расставлены через каждую четверть круга — игра на время, а не на количество кругов.',
        },
        {
          q: 'Почему мотоцикл сносит в поворотах?',
          a: 'Это центробежная сила: она пропорциональна крутизне поворота и квадрату скорости. Чем быстрее вы едете, тем раньше нужно начинать вход в поворот.',
        },
        {
          q: 'Можно ли играть с телефона?',
          a: 'Да. Касание верхней части экрана — газ, нижней — тормоз, а движение пальцем влево-вправо управляет рулём.',
        },
      ],
    },
    en: {
      title: 'Motorbike Rush',
      slug: 'motorbike-3d',
      short: 'Pseudo-3D bike racing: sunset, traffic and a timer that never lasts.',
      metaTitle: 'Motorbike Racing 3D — play online free | GamesIO',
      metaDescription:
        'Arcade third-person motorbike racing in the style of classic Sega cabinets: sunset road, curves, oncoming traffic and checkpoints that extend the clock. Play free in your browser.',
      keywords: ['motorbike racing game', 'hang on game', 'arcade racing online', '3d bike game', 'retro racing game'],
      about: [
        'In 1985 Sega released Hang-On, the first racer where the bike tore toward the horizon while the player leaned with the cabinet itself. Real 3D graphics did not exist yet: the road was assembled from bands that swapped quickly enough to sell the illusion of speed. This game is built the same way.',
        'The track is cut into segments, each drawn as a trapezoid, and a corner is not geometry but a sideways shift applied to every following segment. That is where the handling comes from: speed in a corner throws you outward, and the only way to hold the bike is to hug the inside early. Running onto the shoulder eats your speed instantly, and the clock only extends at checkpoints.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>→</kbd> — lean and steer',
        '<kbd>↑</kbd> or <kbd>Space</kbd> — throttle, <kbd>↓</kbd> — brake',
        'Touch the screen for throttle, slide left/right to steer',
        '<kbd>P</kbd> or <kbd>Esc</kbd> — pause',
      ],
      tips: [
        'Hug the inside of a corner before you reach it: centrifugal force scales with speed, and at the top end it will throw you off the tarmac.',
        'You rarely need the brake. Steering around a car is faster than slowing down, because lost speed takes a long time to rebuild.',
        'The shoulder only drains speed above a third of maximum, so at low speed you can cut a corner across it.',
        'A checkpoint pays +22 seconds. There are four per lap, so the goal is not a clean lap — it is reaching the next gate.',
        'Trucks are wider and slower than cars, which makes them the most dangerous traffic to meet in a blind corner.',
      ],
      faq: [
        {
          q: 'Is this real 3D graphics?',
          a: 'No, and the original Sega cabinets did not have it either. The road is built from flat segments projected onto the screen — a technique called pseudo-3D. That is why the game needs no WebGL and loads instantly.',
        },
        {
          q: 'What does a checkpoint do?',
          a: 'It adds 22 seconds to the clock and 200 points. Gates sit every quarter lap, so this is a time attack rather than a lap race.',
        },
        {
          q: 'Why does the bike slide wide in corners?',
          a: 'That is centrifugal force, proportional to how tight the corner is and to your speed. The faster you go, the earlier you have to start turning in.',
        },
        {
          q: 'Can I play on a phone?',
          a: 'Yes. Touching the upper part of the screen is throttle, the lower part is brake, and sliding your finger left or right steers.',
        },
      ],
    },
  },
  {
    id: 'cars3d',
    emoji: '🚗',
    accent: '#fbbf24',
    categories: ['racing', 'pseudo3d', 'arcade', 'retro'],
    released: '2026-08-04',
    ru: {
      title: 'Реальные тачки',
      slug: 'tachki-3d',
      short: 'Псевдо-3D гонка на машине вдоль побережья: четыре полосы, пальмы, плотный трафик.',
      metaTitle: 'Гонки на машине 3D — играть онлайн бесплатно, как OutRun | GamesIO',
      metaDescription:
        'Аркадная автогонка в стиле OutRun: побережье, пальмы, четыре полосы движения и контрольные точки. Машина тяжелее байка и держит дорогу лучше. Играть в браузере бесплатно.',
      keywords: ['гонки на машине', 'outrun игра', 'аркадные гонки 3д', 'гонки онлайн бесплатно', 'ретро гонки браузер'],
      about: [
        'OutRun вышел в 1986 году и задал жанру тон на десятилетие вперёд: не спорт, а поездка вдоль моря на скорости, к которой не готова ни одна встречная машина. Здесь та же идея — широкая дорога в четыре полосы, пальмы вдоль обочины и таймер, который держит вас в напряжении.',
        'Машина ведёт себя иначе, чем мотоцикл из соседней игры: руль медленнее, зато центробежная сила слабее, а запас скорости выше. Это меняет тактику — вместо резких объездов выгоднее заранее выбрать полосу и держать её, потому что перестроение на четырёхполосной дороге стоит дороже, чем на трёхполосной.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>→</kbd> — руль',
        '<kbd>↑</kbd> или <kbd>Пробел</kbd> — газ, <kbd>↓</kbd> — тормоз',
        'Касание экрана — газ, движение пальцем влево-вправо — руль',
        '<kbd>P</kbd> или <kbd>Esc</kbd> — пауза',
      ],
      tips: [
        'Выбирайте полосу заранее и держитесь её: на четырёх полосах перестроение стоит дороже, чем на трёх.',
        'Внутренняя сторона поворота короче — на длинной дуге это заметная экономия времени.',
        'Каждый обгон даёт 50 очков, поэтому в плотном трафике выгоднее не оттормаживаться, а искать просвет.',
        'Машина держит дорогу лучше байка, но и разгоняется дольше. Потерянные 100 км/ч возвращаются секунды три.',
        'Контрольные точки стоят через каждую четверть круга и дают +24 секунды. Ведите отсчёт от них, а не от круга.',
      ],
      faq: [
        {
          q: 'Чем эта игра отличается от «Реальных мотоциклов»?',
          a: 'Шире дорога (четыре полосы вместо трёх), выше максимальная скорость, медленнее руль и слабее снос в поворотах. Плюс другая трасса и другое окружение — побережье вместо горного заката.',
        },
        {
          q: 'Сколько всего трасс?',
          a: 'Трасса одна, но замкнутая в кольцо и достаточно длинная, чтобы за один заход её целиком не запомнить. Каждый следующий круг даёт 500 очков.',
        },
        {
          q: 'Как начисляются очки?',
          a: 'Постоянно за скорость, плюс 50 за каждый обгон, 200 за контрольную точку и 500 за круг. Гонять медленно и аккуратно невыгодно.',
        },
        {
          q: 'Игра работает на слабом устройстве?',
          a: 'Да. Вся отрисовка — плоские трапеции на обычном 2D-канвасе, без WebGL, шейдеров и загрузки текстур.',
        },
      ],
    },
    en: {
      title: 'Coast Runner',
      slug: 'coast-runner',
      short: 'Pseudo-3D coastal car racing: four lanes, palm trees and heavy traffic.',
      metaTitle: 'Car Racing 3D — play OutRun-style online free | GamesIO',
      metaDescription:
        'Arcade car racing in the style of OutRun: coastline, palm trees, four lanes of traffic and checkpoints. The car is heavier than the bike and holds the road better. Play free in your browser.',
      keywords: ['car racing game', 'outrun game online', 'arcade racing 3d', 'retro racing browser', 'free driving game'],
      about: [
        'OutRun arrived in 1986 and set the tone for a decade: not a sport, but a drive along the sea at a speed no oncoming car is ready for. Same idea here — a wide four-lane road, palm trees on the shoulder and a clock that keeps the pressure on.',
        'The car behaves differently from the bike in the neighbouring game: the steering is slower, but centrifugal force is weaker and the top end is higher. That changes the tactics — instead of darting between cars it pays to pick a lane early and hold it, because changing lanes on a four-lane road costs more than on three.',
      ],
      controls: [
        '<kbd>←</kbd> <kbd>→</kbd> — steer',
        '<kbd>↑</kbd> or <kbd>Space</kbd> — throttle, <kbd>↓</kbd> — brake',
        'Touch the screen for throttle, slide left/right to steer',
        '<kbd>P</kbd> or <kbd>Esc</kbd> — pause',
      ],
      tips: [
        'Pick your lane early and stay in it: on four lanes a lane change costs more than on three.',
        'The inside of a corner is the shorter line, and over a long sweeper that adds up to real time.',
        'Every overtake pays 50 points, so in heavy traffic it is better to find a gap than to lift off.',
        'The car grips better than the bike but also builds speed slower. Losing 100 km/h costs you about three seconds.',
        'Checkpoints sit every quarter lap and add 24 seconds. Count from gate to gate, not lap to lap.',
      ],
      faq: [
        {
          q: 'How is this different from Motorbike Rush?',
          a: 'Wider road (four lanes instead of three), higher top speed, slower steering and less slide in corners. It also has its own track and setting — a coastline instead of a mountain sunset.',
        },
        {
          q: 'How many tracks are there?',
          a: 'One track, but it loops and is long enough that you will not memorise it in a single run. Each completed lap pays 500 points.',
        },
        {
          q: 'How is the score calculated?',
          a: 'Continuously from your speed, plus 50 per overtake, 200 per checkpoint and 500 per lap. Driving slowly and safely does not pay.',
        },
        {
          q: 'Will it run on a weak device?',
          a: 'Yes. Everything is drawn as flat trapezoids on a plain 2D canvas — no WebGL, no shaders, no texture loading.',
        },
      ],
    },
  },
  {
    id: 'duel3d',
    emoji: '🏎️',
    accent: '#f472b6',
    categories: ['racing', 'pseudo3d', 'twoPlayer', 'arcade'],
    released: '2026-08-04',
    ru: {
      title: 'Дуэль на двоих',
      slug: 'duel-na-dvoih',
      short: 'Разделённый экран, одна трасса, три круга. Соперника видно впереди — и его можно подрезать.',
      metaTitle: 'Игра на двоих 3D — гонка на одной клавиатуре бесплатно | GamesIO',
      metaDescription:
        'Псевдо-3D гонка на двоих за одной клавиатурой: разделённый экран, общая трасса, три круга. Первый игрок — WASD, второй — стрелки. Играть в браузере бесплатно.',
      keywords: ['игры на двоих', 'гонки на двоих', 'игра на одной клавиатуре', 'сплит скрин гонки', 'игры на двоих онлайн'],
      about: [
        'Гонка на разделённом экране — жанр, который почти исчез из браузера вместе с локальным мультиплеером. Здесь он в чистом виде: два игрока за одной клавиатурой, одна трасса на двоих, три круга и никакого интернета.',
        'Важная деталь: соперник не нарисован отдельно в каждом виде, а живёт на трассе как объект. Поэтому если он едет впереди, вы видите его машину на дороге — в неё можно врезаться, её можно подрезать и ею можно закрыть проезд в повороте. Это превращает гонку в контактную борьбу, а не в две параллельные поездки.',
      ],
      controls: [
        'Игрок 1: <kbd>W</kbd> <kbd>A</kbd> <kbd>S</kbd> <kbd>D</kbd> — газ, руль, тормоз',
        'Игрок 2: <kbd>↑</kbd> <kbd>←</kbd> <kbd>↓</kbd> <kbd>→</kbd> — газ, руль, тормоз',
        '<kbd>P</kbd> или <kbd>Esc</kbd> — пауза',
        'Нужна клавиатура: на телефоне вдвоём не сыграть',
      ],
      tips: [
        'Идущий вторым видит соперника впереди — этим стоит пользоваться: держитесь за ним и уходите в сторону только на выходе из поворота.',
        'Лидеру выгодно занимать внутреннюю сторону поворота: он и короче, и закрывает сопернику удобную траекторию.',
        'Столкновение сбрасывает скорость обоим, но отбрасывает того, кто ехал быстрее. Таранить лидера сзади невыгодно.',
        'Три круга — дистанция, на которой одна ошибка ещё отыгрывается. Не рискуйте на первом.',
        'Съезд на обочину отнимает скорость только на быстром ходу, поэтому спрямлять углы на выходе из поворота иногда выгодно.',
      ],
      faq: [
        {
          q: 'Можно играть по сети?',
          a: 'Нет, это локальная игра за одной клавиатурой. Никакого сервера у сайта нет, всё работает прямо в браузере.',
        },
        {
          q: 'Кто побеждает?',
          a: 'Тот, кто первым закончит три круга. Итог показывается на весь экран, после чего партию можно начать заново.',
        },
        {
          q: 'Клавиши не мешают друг другу?',
          a: 'Первый игрок использует WASD, второй — стрелки, эти блоки на большинстве клавиатур обрабатываются независимо. На дешёвых мембранных клавиатурах при трёх одновременных нажатиях возможны пропуски — это ограничение железа.',
        },
        {
          q: 'Можно ли сыграть одному?',
          a: 'Технически да — вторая машина просто останется на старте. Но игра рассчитана на двоих; для одиночной гонки есть «Реальные тачки» и «Реальные мотоциклы».',
        },
      ],
    },
    en: {
      title: 'Split Duel',
      slug: 'split-duel',
      short: 'Split screen, one track, three laps. You can see your rival ahead — and cut him off.',
      metaTitle: 'Two Player Game 3D — split-screen race on one keyboard | GamesIO',
      metaDescription:
        'Pseudo-3D two player racing on a single keyboard: split screen, shared track, three laps. Player one uses WASD, player two the arrow keys. Play free in your browser.',
      keywords: ['two player games', '2 player racing', 'split screen game', 'same keyboard game', 'local multiplayer browser'],
      about: [
        'Split-screen racing is a genre that all but vanished from the browser along with local multiplayer. Here it is in its purest form: two players on one keyboard, one shared track, three laps and no internet involved.',
        'One detail matters: the rival is not drawn separately in each view — he exists on the track as an object. So when he is ahead, you see his actual car on the road. You can hit it, cut him off, and block the racing line through a corner. That turns the race into contact fighting rather than two parallel drives.',
      ],
      controls: [
        'Player 1: <kbd>W</kbd> <kbd>A</kbd> <kbd>S</kbd> <kbd>D</kbd> — throttle, steer, brake',
        'Player 2: <kbd>↑</kbd> <kbd>←</kbd> <kbd>↓</kbd> <kbd>→</kbd> — throttle, steer, brake',
        '<kbd>P</kbd> or <kbd>Esc</kbd> — pause',
        'Keyboard required: two people cannot share a phone screen',
      ],
      tips: [
        'Running second means you can see your rival — use it. Sit behind him and only pull out on corner exit.',
        'The leader should take the inside line: it is shorter and it denies the rival the comfortable trajectory.',
        'A collision costs both of you speed but throws off whoever was going faster. Ramming the leader from behind does not pay.',
        'Three laps is long enough to recover from one mistake, so do not take risks on the first.',
        'The shoulder only drains speed at high pace, so straightening a corner exit across it is sometimes worth it.',
      ],
      faq: [
        {
          q: 'Can we play over the internet?',
          a: 'No, this is local play on one keyboard. The site has no server at all — everything runs in your browser.',
        },
        {
          q: 'Who wins?',
          a: 'Whoever completes three laps first. The result is shown full screen, and you can restart the race from there.',
        },
        {
          q: 'Do the two key sets interfere?',
          a: 'Player one uses WASD and player two the arrows; on most keyboards these blocks register independently. Cheap membrane keyboards can drop a third simultaneous key — that is a hardware limit, not the game.',
        },
        {
          q: 'Can I play alone?',
          a: 'Technically yes — the second car simply stays on the grid. But the game is built for two; for solo racing try Coast Runner or Motorbike Rush.',
        },
      ],
    },
  },
];

/* Скрипты страницы. Порядок важен: движок, общие библиотеки, игры, оболочка.
   Один список на генератор страниц и на однофайловую сборку — чтобы при
   добавлении игры не пришлось помнить про два места. */
const SCRIPTS = [
  'src/js/engine.js',
  'src/js/lib/scores.js',
  'src/js/lib/pwa.js',
  'src/js/lib/tilemap.js',
  'src/js/lib/road.js',
  'src/js/lib/racer.js',
  'src/js/games/arkanoid.js',
  'src/js/games/snake.js',
  'src/js/games/moto.js',
  'src/js/games/moto3d.js',
  'src/js/games/cars3d.js',
  'src/js/games/duel3d.js',
  'src/js/games/planes.js',
  'src/js/games/tanks.js',
  'src/js/games/contra.js',
  'src/js/games/sonic.js',
  'src/js/ads.js',
  'src/js/app.js',
  'src/js/ui.js',
];

module.exports = { SITE, UI, CATEGORIES, GAMES, SCRIPTS };
